function [res_seg, corrected, field] = generate_mask(result)
% Function to generate segmentation results from SPM12 probability maps
% result              - struct with filenames of the segmentation results
%                       generated by SPM

% 
% OUTPUT: 
% res_seg            - segmentation result for CSF, GM, WM
% corrected          - brain volume after bias field correction
% field              - the bias field corrected by SPM

% Read tissue probability maps
    gm = niftiread(result.gm_fn(1:end-2));
    wm = niftiread(result.wm_fn(1:end-2));
    csf = niftiread(result.csf_fn(1:end-2));
    bone = niftiread(result.bone_fn(1:end-2));
    soft = niftiread(result.soft_fn(1:end-2));
    air = niftiread(result.air_fn(1:end-2));
    corrected = niftiread(result.correct_fn(1:end-2));
    field = niftiread(result.field_fn(1:end-2));
    
    % Classify the tissues according to maximum a posteriori probabilies
    maps = zeros(240, 240, 48, 6); 
    maps(:, :, :, 1) = csf; 
    maps(:, :, :, 2) = gm;
    maps(:, :, :, 3) = wm;
    maps(:, :, :, 4) = bone;
    maps(:, :, :, 5) = soft;
    maps(:, :, :, 6) = air;
    [~, res_seg] = max(maps, [], 4);
    
    % Ignore bone, soft tissue and air
    res_seg(res_seg>3) = 0;
end

