function metrics = get_metrics(res_seg, labels, volume, correct)
% Function to calculate statistics and metrics from the segmentation
% results generated by SPM
% res_seg            - resulting segmentation masks
% labels             - ground truth 
% volume             - the original brain scan
% correcy            - the volume after bias field correction
% 
% OUTPUT: 
% metrics            - array of 16 metrics calculated from the segmentation
% result: CSF dice, GM dice, WM dice, Average Dice, the mean and standard
% deviation of intensities of each tissue in both the original and
% corrected brain scans based on the masks in res_seg


dice_score = dice(res_seg, labels); 

csf_mask = int16(res_seg == 1);
gm_mask =  int16(res_seg == 2);
wm_mask =  int16(res_seg == 3);

csf_original = volume .* csf_mask;
csf_correct = int16(correct) .* csf_mask;

gm_original = volume .* gm_mask;
gm_correct = int16(correct) .* gm_mask;

wm_original = volume .* wm_mask;
wm_correct = int16(correct) .* wm_mask;

csf_o_mean = mean(csf_original(csf_original~=0));
csf_c_mean = mean(csf_correct(csf_correct~=0));
csf_o_std = std(double(csf_original(csf_original~=0)));
csf_c_std = std(double(csf_correct(csf_correct~=0)));

gm_o_mean = mean(gm_original(gm_original~=0));
gm_c_mean = mean(gm_correct(gm_correct~=0));
gm_o_std = std(double(gm_original(gm_original~=0)));
gm_c_std = std(double(gm_correct(gm_correct~=0)));

wm_o_mean = mean(wm_original(wm_original~=0));
wm_c_mean = mean(wm_correct(wm_correct~=0));
wm_o_std = std(double(wm_original(wm_original~=0)));
wm_c_std = std(double(wm_correct(wm_correct~=0)));

metrics = [dice_score(1), dice_score(2), dice_score(3), mean(dice_score) ... 
           csf_o_mean, csf_c_mean csf_o_std, csf_c_std ...
           gm_o_mean, gm_c_mean, gm_o_std, gm_c_std ...
           wm_o_mean, wm_c_mean, wm_o_std, wm_c_std];
end

